kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app_name: {{ .Chart.Name }}
    app_version: {{ .Values.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http-port
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.targetPort }}
    type: {{ .Values.ports.type }}
  selector:
    app_name: {{ .Chart.Name }}
